server:
  port: 8081
spring:
  application:
    name: xunhang-service
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunhang
#    url: jdbc:mysql://101.35.223.149:3306/xunhang
    username: root
    password: mysql密码
  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 100MB
      enabled: true
  redis:
    host: redis ip
    port: 6379
    password: redis密码
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
    virtual-host: /
    # 消息确认（ACK）
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)

minio:
  endpoint: http://121.41.27.33:9001 #内网地址
  public: http://121.41.27.33:9001  #外网访问地址
  accessKey: root
  secretKey: minio密码
  bucketName: xunhang
  maxImageSize: 5242880
  maxnFileSize: 5242880 # 5 * 1024 * 1024


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.xunhang.pojo.entity
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



