spring:
  profiles:
    active: dev

xunhang:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: MIIBIjANBgkq
    # 设置jwt过期时间
    admin-ttl: 5184000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: MIIBIjANBgkq
    user-ttl: 5184000000
    user-token-name: authentication
    refresh-token-secret: IKDiqVmn0VFU
    refresh-token-expire-in: 604800 #7天
  alioss:
    access-key: 阿里云key
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: 阿里云secret
    bucket-name: xunhang
  wechat:
    appid: wx569461cd45719772
    secret: wechatsecret
