server:
  port: 8081
spring:
  application:
    name: xunhang-service
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunhang
#    url: jdbc:mysql://101.35.223.149:3306/xunhang
    username: root
    password: ckc531213
  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 100MB
      enabled: true
  redis:
    host: 116.198.233.46
    port: 6379
    password: ckc531213
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
    virtual-host: /
    # 消息确认（ACK）
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)

minio:
  endpoint: http://121.41.27.33:9001 #内网地址
  public: http://121.41.27.33:9001  #外网访问地址
  accessKey: root
  secretKey: ckc531213
  bucketName: xunhang
  maxImageSize: 5242880
  maxnFileSize: 5242880 # 5 * 1024 * 1024


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.xunhang.pojo.entity
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



logging:
  level:
    #    com.baomidou.mybatisplus: debug
    com.xunhang.mapper: debug

xunhang:
  file:
    storage:
      # 是否开启服务 1开启 0关闭
      minio:${xunhang.file.storage.minio:1} 
      aliyunoss:${xunhang.file.storage.aliyunoss:1}
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: MIIBIjANBgkq
    # 设置jwt过期时间
    admin-ttl: 5184000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: MIIBIjANBgkq
    user-ttl: 5184000000
    user-token-name: authentication
    refresh-token-secret: IKDiqVmn0VFU
    refresh-token-expire-in: 604800 #7天
  alioss:
    access-key: LTAI5tLmD6fA9X52AZcp1XhG
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: txaI5kUqbWtV8cCMc1we3idGpDHI7d
    bucket-name: xunhang
  wechat:
    appid: wx569461cd45719772
    secret: d901af658052f55ad70fc91ac46fdcba
