server:
  port: 8888
spring:
  application:
    name: im-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunhang?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: ckc531213
  redis:
    host: 116.198.233.46
    port: 6379
    password: ckc531213

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:mapper/*.xml
#minio:
#  endpoint: http://127.0.0.1:9000 #内网地址
#  public: http://127.0.0.1:9000  #外网访问地址
#  accessKey: admin
#  secretKey: 12345678
#  bucketName: box-im
#  imagePath: image
#  filePath: file
#  videoPath: video

#webrtc:
#  iceServers:
#    - urls: stun:stun.l.google.com:19302

jwt:
  accessToken:
    expireIn: 180000 #半个小时
    secret: MIIBIjANBgkq
  refreshToken:
    expireIn: 604800 #7天
    secret: IKDiqVmn0VFU

